sudo: required
language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: clang
    - os: osx
      compiler: gcc

before_install:
  - eval "${MATRIX_EVAL}"
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -qq update; fi
    # apt-get only have swig 2.0.11
  - if [ $TRAVIS_OS_NAME == linux ]; then
    cd /tmp/;
      curl -s -J -O -k -L 'https://sourceforge.net/projects/swig/files/swig/swig-3.0.12/swig-3.0.12.tar.gz/download';
      tar zxf swig-3.0.12.tar.gz;
      cd swig-3.0.12;
      ./configure --prefix $HOME/swig/;
      make;
      make install;
      cd $TRAVIS_BUILD_DIR;
    fi
    # work around https://github.com/travis-ci/travis-ci/issues/8363
  - if [ $TRAVIS_OS_NAME == linux ]; then pyenv global system 3.6; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then python3.6 --version; python3.6 -m pip --version; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then python3.6 -m pip install virtualenv; fi

  - if [ $TRAVIS_OS_NAME == osx ]; then sudo chown -R $(whoami) /usr/local; fi
    # work around https://github.com/travis-ci/travis-ci/issues/8552
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install swig; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install python3; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then python3 --version; python3 -m pip --version; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then python3 -m pip install virtualenv; fi


script:
  - cmake --version
  - swig --version
  - cmake -H. -Bbuild
  - cmake --build build --target all
  - cmake --build build --target test
